spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: root1234!!
  jpa:
    show-sql: true
    properties:
      format_sql: true
      highlight_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
